_wandb:
    value:
        cli_version: 0.21.4
        e:
            iaoo22buj8azokwh7me33nkvlctn462i:
                cpu_count: 20
                cpu_count_logical: 20
                disk:
                    /:
                        total: "539426451456"
                        used: "152826408960"
                email: schuppsimon5@gmail.com
                executable: /nix/store/qsg98l1y41k4530xsn0ss82xrd03095c-python3-3.12.11-env/bin/python3.12
                git:
                    commit: 2eb0482a5984eee8fd9625ae8fd7f439e86e85b9
                    remote: git@github-personal.com:LuposX/SpikeSynth.git
                host: logos
                memory:
                    total: "33063743488"
                os: Linux-6.12.49-x86_64-with-glibc2.40
                program: surrogate/Lighning_Pipeline.ipynb
                python: CPython 3.12.11
                root: /home/monkeman/SpikeSynth/surrogate
                startedAt: "2025-10-17T13:29:43.469597Z"
                writerId: iaoo22buj8azokwh7me33nkvlctn462i
        m: []
        python_version: 3.12.11
        session_history: code/_session_history.ipynb
        t:
            "1":
                - 1
                - 9
                - 103
            "2":
                - 1
                - 9
                - 103
            "3":
                - 2
            "4": 3.12.11
            "5": 0.21.4
            "8":
                - 1
            "12": 0.21.4
            "13": linux-x86_64
