wandb_version: 1

batch_size:
  value: 1024
beta:
  value: 0.85
epochs:
  value: 25
gamma:
  value: 0.99
lr:
  value: 0.001
num_hidden:
  value: 64
num_hidden_layers:
  value: 8
optimizer_class:
  value: SGD
