wandb_version: 1

batch_size:
  value: 4096
beta:
  value: 0.95
epochs:
  value: 25
gamma:
  value: 0.99
lr:
  value: 0.0005
num_hidden:
  value: 256
num_hidden_layers:
  value: 8
optimizer_class:
  value: AdamW
