wandb_version: 1

batch_size:
  value: 1024
beta:
  value: 0.9
epochs:
  value: 25
gamma:
  value: 0.9
lr:
  value: 0.001
num_hidden:
  value: 32
num_hidden_layers:
  value: 8
optimizer_class:
  value: AdamW
