wandb_version: 1

batch_size:
  value: 2048
beta:
  value: 0.9
epochs:
  value: 25
gamma:
  value: 0.95
lr:
  value: 0.01
num_hidden:
  value: 64
num_hidden_layers:
  value: 1
optimizer_class:
  value: Adam
