wandb_version: 1

batch_size:
  value: 2048
beta:
  value: 0.95
epochs:
  value: 25
gamma:
  value: 0.9
lr:
  value: 0.001
num_hidden:
  value: 256
num_hidden_layers:
  value: 2
optimizer_class:
  value: AdamW
