_wandb:
    value:
        cli_version: 0.21.4
        code_path: code/surrogate/train_sweep_model.py
        e:
            g0p3cf14esyuoqbfhpjb5ez9msmrwaa5:
                args:
                    - --batch_size=4096
                    - --beta=0.85
                    - --epochs=25
                    - --gamma=0.9
                    - --lr=0.005
                    - --num_hidden=32
                    - --optimizer_class=torch.optim.AdamW
                codePath: surrogate/train_sweep_model.py
                codePathLocal: train_sweep_model.py
                email: schuppsimon5@gmail.com
                executable: /nix/store/qsg98l1y41k4530xsn0ss82xrd03095c-python3-3.12.11-env/bin/python3.12
                git:
                    commit: 2eb0482a5984eee8fd9625ae8fd7f439e86e85b9
                    remote: git@github-personal.com:LuposX/SpikeSynth.git
                host: logos
                os: Linux-6.12.49-x86_64-with-glibc2.40
                program: /home/monkeman/SpikeSynth/surrogate/train_sweep_model.py
                python: CPython 3.12.11
                root: /home/monkeman/SpikeSynth/surrogate
                startedAt: "2025-10-17T14:49:29.490154Z"
                writerId: g0p3cf14esyuoqbfhpjb5ez9msmrwaa5
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 9
                - 103
            "2":
                - 1
                - 9
                - 103
            "3":
                - 14
            "4": 3.12.11
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 4096
beta:
    value: 0.85
epochs:
    value: 25
gamma:
    value: 0.9
lr:
    value: 0.005
num_hidden:
    value: 32
optimizer_class:
    value: torch.optim.AdamW
