_wandb:
    value:
        cli_version: 0.21.4
        code_path: code/surrogate/train_sweep_model.py
        e:
            iljmyq5cvlojt7kni9c3oa16dhxt0gxo:
                args:
                    - --batch_size=2048
                    - --beta=0.95
                    - --epochs=2
                    - --gamma=0.95
                    - --lr=0.001
                    - --num_hidden=64
                codePath: surrogate/train_sweep_model.py
                codePathLocal: train_sweep_model.py
                email: schuppsimon5@gmail.com
                executable: /nix/store/qsg98l1y41k4530xsn0ss82xrd03095c-python3-3.12.11-env/bin/python3.12
                git:
                    commit: 2eb0482a5984eee8fd9625ae8fd7f439e86e85b9
                    remote: git@github-personal.com:LuposX/SpikeSynth.git
                host: logos
                os: Linux-6.12.49-x86_64-with-glibc2.40
                program: /home/monkeman/SpikeSynth/surrogate/train_sweep_model.py
                python: CPython 3.12.11
                root: /home/monkeman/SpikeSynth/surrogate
                startedAt: "2025-10-17T14:18:38.373722Z"
                writerId: iljmyq5cvlojt7kni9c3oa16dhxt0gxo
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 9
                - 103
            "2":
                - 1
                - 9
                - 103
            "3":
                - 14
            "4": 3.12.11
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 2048
beta:
    value: 0.95
epochs:
    value: 2
gamma:
    value: 0.95
lr:
    value: 0.001
num_hidden:
    value: 64
