_wandb:
    value:
        cli_version: 0.21.4
        e:
            etw6d1lzxsqd7fcqo2ib28q1t028gtlr:
                cpu_count: 20
                cpu_count_logical: 20
                disk:
                    /:
                        total: "539426451456"
                        used: "147256496128"
                email: schuppsimon5@gmail.com
                executable: /nix/store/qsg98l1y41k4530xsn0ss82xrd03095c-python3-3.12.11-env/bin/python3.12
                git:
                    commit: 2eb0482a5984eee8fd9625ae8fd7f439e86e85b9
                    remote: git@github-personal.com:LuposX/SpikeSynth.git
                host: logos
                memory:
                    total: "33063743488"
                os: Linux-6.12.49-x86_64-with-glibc2.40
                program: surrogate/Lighning_Pipeline.ipynb
                python: CPython 3.12.11
                root: .
                startedAt: "2025-10-17T09:20:20.096993Z"
                writerId: etw6d1lzxsqd7fcqo2ib28q1t028gtlr
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 9
                - 103
            "2":
                - 1
                - 9
                - 103
            "3":
                - 1
                - 7
                - 13
                - 62
                - 66
            "4": 3.12.11
            "5": 0.21.4
            "8":
                - 1
            "12": 0.21.4
            "13": linux-x86_64
