_wandb:
    value:
        cli_version: 0.21.4
        code_path: code/surrogate/train_sweep_rsnn_model.py
        e:
            djb3og8wfknwpb0ocs5b2uqyg0idk05i:
                args:
                    - --batch_size=1024
                    - --beta=0.9
                    - --epochs=25
                    - --gamma=0.95
                    - --lr=0.001
                    - --num_hidden=64
                    - --num_hidden_layers=4
                    - --optimizer_class=AdamW
                codePath: surrogate/train_sweep_rsnn_model.py
                codePathLocal: train_sweep_rsnn_model.py
                cpu_count: 20
                cpu_count_logical: 20
                disk:
                    /:
                        total: "539426451456"
                        used: "144567365632"
                email: schuppsimon5@gmail.com
                executable: /nix/store/qsg98l1y41k4530xsn0ss82xrd03095c-python3-3.12.11-env/bin/python3.12
                git:
                    commit: 2eb0482a5984eee8fd9625ae8fd7f439e86e85b9
                    remote: git@github-personal.com:LuposX/SpikeSynth.git
                host: logos
                memory:
                    total: "33063739392"
                os: Linux-6.12.49-x86_64-with-glibc2.40
                program: /home/monkeman/SpikeSynth/surrogate/train_sweep_rsnn_model.py
                python: CPython 3.12.11
                root: /home/monkeman/SpikeSynth/surrogate
                startedAt: "2025-10-20T16:16:14.007749Z"
                writerId: djb3og8wfknwpb0ocs5b2uqyg0idk05i
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 9
                - 103
            "2":
                - 1
                - 9
                - 103
            "3":
                - 1
                - 2
                - 14
                - 62
            "4": 3.12.11
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 1024
beta:
    value: 0.9
epochs:
    value: 25
gamma:
    value: 0.95
lr:
    value: 0.001
num_hidden:
    value: 64
num_hidden_layers:
    value: 4
optimizer_class:
    value: AdamW
