wandb_version: 1

batch_size:
  value: 4096
beta:
  value: 0.85
epochs:
  value: 25
gamma:
  value: 0.99
lr:
  value: 0.0005
num_hidden:
  value: 512
num_hidden_layers:
  value: 2
optimizer_class:
  value: AdamW
