wandb_version: 1

batch_size:
  value: 1024
beta:
  value: 0.95
epochs:
  value: 25
gamma:
  value: 0.99
lr:
  value: 0.005
num_hidden:
  value: 64
num_hidden_layers:
  value: 2
optimizer_class:
  value: AdamW
